[localhost]
ansplcbsstpc1pr.amer.dell.com

[localhost:vars]
ansible_user=svc_prdprdpheptapcf

[entrocim_cyb_p]
emsplkul01.apac.dell.com
emsplkul02.apac.dell.com
emsplpen103.apac.dell.com

[entrocim_cyb_p:vars]
region=apac

[entrocim_pen1_p]
emsplpen101.apac.dell.com
emsplpen102.apac.dell.com
emsplkul03.apac.dell.com

[entrocim_pen1_p:vars]
region=apac

[entrocim_pen2_p]
emsplpen201.apac.dell.com
emsplpen202.apac.dell.com

[entrocim_pen2_p:vars]
region=apac

[entrocim_jpn_p]
emspljpt01.apac.dell.com
emspljpt02.apac.dell.com

[entrocim_jpn_p:vars]
region=apac

[entrocim_lim_p]
emsplsnn01.emea.dell.com
emsplsnn02.emea.dell.com
emsplork1app03.emea.dell.com

[entrocim_lim_p:vars]
region=emea

[entrocim_crk_p]
emsplork1app01.emea.dell.com
emsplork1app02.emea.dell.com
emsplsnn03.emea.dell.com

[entrocim_crk_p:vars]
region=emea

[entrocim_ldz_p]
emspllcj01.emea.dell.com
emspllcj02.emea.dell.com

[entrocim_ldz_p:vars]
region=emea

[entrocim_pc1_p]
#emsplpc101.amer.dell.com 
#emsplpc102.amer.dell.com 
#emspls3b03.amer.dell.com

[entrocim_pc1_p:vars]
#region=amer

[entrocim_s3b_p]
emspls3b01.amer.dell.com 
emspls3b02.amer.dell.com 
emsplpc103.amer.dell.com 

[entrocim_s3b_p:vars]
region=amer

[entrocim_dur_p]
emspldur01.amer.dell.com 
emspldur02.amer.dell.com 

[entrocim_dur_p:vars]
region=amer

[entrocim_cyb_np]
emsnlkuldev01.apac.dell.com
emsnlkuldev02.apac.dell.com

[entrocim_cyb_np:vars]
region=apac

[entrocim_ctu6_p]
emsplctu6app01.ctu.apac.dell.com
emsplctu6app02.ctu.apac.dell.com

[entrocim_ctu6_p:vars]
region=apac

[entrocim_xmn4_p]
emsplxmn4app01.xmn.apac.dell.com
emsplxmn4app02.xmn.apac.dell.com

[entrocim_xmn4_p:vars]
region=apac

[entrocim_frk_p]
emsplbos1app01.amer.dell.com
emsplbos1app02.amer.dell.com

[entrocim_frk_p:vars]
region=amer

[entrocim_apex_p]
emsplrdu1app01.amer.dell.com
emsplrdu1app02.amer.dell.com

[entrocim_apex_p:vars]
region=amer

[entrocim_chen_p]
emsplicc1app01.apac.dell.com
emsplicc1app02.apac.dell.com

[entrocim_chen_p:vars]
region=apac

[entrocim_dell6_p]
emsplblr601.apac.dell.com
emsplblr602.apac.dell.com 

[entrocim_dell6_p:vars]
region=apac

[entrocim_hor_p]
emsplhorapp01.amer.dell.com
emsplhorapp02.amer.dell.com

[entrocim_hor_p:vars]
region=amer

[entrocim_rtp_p]
emsplrtp01.amer.dell.com
emsplrtp02.amer.dell.com

[entrocim_rtp_p:vars]
region=amer

[entrocim_lvg_lab]
zzzplhepta01.amer.dell.com
zzzplhepta02.amer.dell.com

[entrocim_lvg_lab:vars]
region=amer

[entrocim_apac_p]
emsplkul01.apac.dell.com
emsplkul02.apac.dell.com
emsplkul03.apac.dell.com
emsplpen101.apac.dell.com
emsplpen102.apac.dell.com
emsplpen103.apac.dell.com 
emsplpen201.apac.dell.com
emsplpen202.apac.dell.com
emsplxmn4app01.xmn.apac.dell.com
emsplxmn4app02.xmn.apac.dell.com
emsplctu6app01.ctu.apac.dell.com
emsplctu6app02.ctu.apac.dell.com
emsplicc1app01.apac.dell.com
emsplicc1app02.apac.dell.com
emsplblr601.apac.dell.com
emsplblr602.apac.dell.com 

[entrocim_apac_p:vars]
region=apac

[entrocim_emea_p]
emsplork1app01.emea.dell.com
emsplork1app02.emea.dell.com
emsplork1app03.emea.dell.com
emsplsnn03.emea.dell.com
emsplsnn01.emea.dell.com
emsplsnn02.emea.dell.com
emspllcj01.emea.dell.com
emspllcj02.emea.dell.com

[entrocim_emea_p:vars]
region=emea

[entrocim_amer_p]
emsplrtp01.amer.dell.com
emsplrtp02.amer.dell.com
emsplbos1app01.amer.dell.com
emsplbos1app02.amer.dell.com
emsplrdu1app01.amer.dell.com
emsplrdu1app02.amer.dell.com
emsplpc103.amer.dell.com 
emspls3b01.amer.dell.com 
emspls3b02.amer.dell.com
emsplhorapp01.amer.dell.com
emsplhorapp02.amer.dell.com

[entrocim_amer_p:vars]
region=amer

[entrocim_all_preprod]
emspljpt01.apac.dell.com
emspljpt02.apac.dell.com
#emsplpc101.amer.dell.com 
#emsplpc102.amer.dell.com  
#emspls3b03.amer.dell.com
emspldur01.amer.dell.com 
emspldur02.amer.dell.com

[entrocim_all_preprod:vars]
ansible_user=svc_prdprdpheptapcf 

[entrocim_all_p]
emsplkul01.apac.dell.com
emsplkul02.apac.dell.com
emsplkul03.apac.dell.com
emsplpen101.apac.dell.com
emsplpen102.apac.dell.com
emsplpen103.apac.dell.com
emsplpen201.apac.dell.com
emsplpen202.apac.dell.com
emsplork1app01.emea.dell.com
emsplork1app02.emea.dell.com
emsplork1app03.emea.dell.com
emsplsnn03.emea.dell.com
emsplsnn01.emea.dell.com
emsplsnn02.emea.dell.com
emspllcj01.emea.dell.com
emspllcj02.emea.dell.com
emsplxmn4app01.xmn.apac.dell.com
emsplxmn4app02.xmn.apac.dell.com
emsplctu6app01.ctu.apac.dell.com
emsplctu6app02.ctu.apac.dell.com
emsplrtp01.amer.dell.com
emsplrtp02.amer.dell.com
emsplbos1app01.amer.dell.com
emsplbos1app02.amer.dell.com
emsplrdu1app01.amer.dell.com
emsplrdu1app02.amer.dell.com
emsplicc1app01.apac.dell.com
emsplicc1app02.apac.dell.com
emsplblr601.apac.dell.com
emsplblr602.apac.dell.com 
emsplpc103.amer.dell.com 
emspls3b01.amer.dell.com 
emspls3b02.amer.dell.com
emsplhorapp01.amer.dell.com
emsplhorapp02.amer.dell.com

[entrocim_all_p:vars]
ansible_user=svc_prdprdpheptapcf 

[entrocim_all_np]
emsnlkuldev01.apac.dell.com
emsnlkuldev02.apac.dell.com
zzzplhepta01.amer.dell.com
zzzplhepta02.amer.dell.com

[entrocim_all_np:vars]
ansible_user=svc_npdevheptapcf 

[gso_camera_checker]
verpwduramrec03.corp.emc.com
gappwsvrcatalog.amer.dell.com
ongnwsqrdev19.aus.amer.dell.com

[sauter]
sbmpwcrkdb01.emea.dell.com

[sauter:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[tags]
ausfacitsmtdb.aus.amer.dell.com

[tags:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_npdevheptapcf@AMER.DELL.COM

[sitescan]
scnpwpc1app01.aus.amer.dell.com
scnpwpc1app02.aus.amer.dell.com
scnpws3bapp01.aus.amer.dell.com

[sitescan:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[webctrl]
wctpwpc1app01.aus.amer.dell.com
wctpwpc1app02.aus.amer.dell.com
wctpws3bapp01.aus.amer.dell.com

[webctrl:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[metasys_ctx_p]
jcipwctxhapp01.aus.amer.dell.com

[metasys_ctx_p:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[metasys_sct_ctx_p]
jcipwctxsct01.aus.amer.dell.com

[metasys_sct_ctx_p:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[metasys_ctx_np]
jcinwctxhapp01.aus.amer.dell.com

[metasys_ctx_np:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[metasys_dur_p]
jcipwdurhapp01.amer.dell.com

[metasys_dur_p:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM

[metasys_sct_dur_p]
jcipwdurhsct01.amer.dell.com

[metasys_sct_dur_p:vars]
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=svc_prdprdpheptapcf@AMER.DELL.COM
